# Generated by Django 4.1.2 on 2023-01-03 16:40

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=50)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('multiple_answer_questions', models.BooleanField(default=False)),
                ('time', models.PositiveSmallIntegerField(default=0)),
                ('question_amount', models.PositiveSmallIntegerField(default=0)),
                ('lesson_amount', models.PositiveSmallIntegerField(default=0)),
                ('attempt_amount', models.PositiveSmallIntegerField(default=3)),
                ('test_ready', models.BooleanField(default=False)),
                ('passing_score', models.PositiveSmallIntegerField(default=0)),
                ('category', models.CharField(default='', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=3000)),
                ('logo', models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/logos', location='media/logos'), upload_to='')),
                ('inactive', models.BooleanField(default=False)),
                ('users', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StudentGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(to='exam.course')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.platform')),
                ('students', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('finished', models.BooleanField(default=False)),
                ('current_score', models.PositiveSmallIntegerField(default=False)),
                ('current_question', models.PositiveSmallIntegerField(default=1)),
                ('question_order', models.CharField(max_length=2000, null=True)),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('end_time', models.DateTimeField(null=True)),
                ('passed', models.BooleanField(default=False)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=1000)),
                ('answer1', models.CharField(max_length=200)),
                ('answer2', models.CharField(max_length=200)),
                ('answer3', models.CharField(blank=True, max_length=200, null=True)),
                ('answer4', models.CharField(blank=True, max_length=200, null=True)),
                ('answer5', models.CharField(blank=True, max_length=200, null=True)),
                ('correct_answers', models.CharField(max_length=50)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
            ],
        ),
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('topic', models.CharField(max_length=100)),
                ('material', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/lessons', location='media/lessons'), upload_to='')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
            ],
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('bar', models.PositiveSmallIntegerField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.platform')),
            ],
        ),
        migrations.CreateModel(
            name='Deadline',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.studentgroup')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='platform',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.platform'),
        ),
        migrations.AddField(
            model_name='course',
            name='students',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
