# Generated by Django 4.1.2 on 2023-01-08 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='changable_logo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='platform',
            name='course_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platform',
            name='course_per_group_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platform',
            name='group_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platform',
            name='lesson_per_course_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platform',
            name='student_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='platform',
            name='student_per_group_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
