# Generated by Django 4.1.2 on 2023-01-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_platform_changable_logo_platform_course_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='question_per_course_limit',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
