# Generated by Django 4.1 on 2022-08-24 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_alter_course_students_alter_result_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='radio_questions',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
