# Generated by Django 4.1 on 2022-08-25 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0003_course_radio_questions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='radio_questions',
        ),
        migrations.AddField(
            model_name='course',
            name='multiple_answer_questions',
            field=models.BooleanField(default=False),
        ),
    ]
