# Generated by Django 4.1 on 2022-08-27 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_alter_question_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='question',
            name='course',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='exam.course'),
        ),
    ]
