# Generated by Django 4.1 on 2022-08-27 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0007_alter_question_correct_answers_alter_question_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.CharField(max_length=1000),
        ),
    ]
