# Generated by Django 4.1 on 2022-08-28 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_alter_question_correct_answers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answers',
        ),
        migrations.AddField(
            model_name='question',
            name='answer1',
            field=models.CharField(default='p', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer2',
            field=models.CharField(default='p', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='answer3',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer4',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='question',
            name='answer5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answers',
            field=models.CharField(max_length=20),
        ),
    ]
