# Generated by Django 4.1 on 2022-08-29 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0011_alter_question_correct_answers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.FileField(upload_to='lessons'),
        ),
    ]
