# Generated by Django 4.1 on 2022-08-29 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_alter_lesson_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='title',
            field=models.CharField(default='p', max_length=100),
            preserve_default=False,
        ),
    ]
