# Generated by Django 4.1 on 2022-08-29 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0013_lesson_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lesson',
            old_name='title',
            new_name='topic',
        ),
    ]
