# Generated by Django 4.1 on 2022-09-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0014_rename_title_lesson_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.FileField(upload_to=''),
        ),
    ]
