# Generated by Django 4.1 on 2022-09-04 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_alter_lesson_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.FileField(upload_to='lessons'),
        ),
    ]
