# Generated by Django 4.1 on 2022-09-05 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0016_alter_lesson_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='time',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
