# Generated by Django 4.1 on 2022-09-06 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_course_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='question_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
