# Generated by Django 4.1 on 2022-09-15 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0018_course_question_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='lesson_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='student_amount',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
