# Generated by Django 4.1 on 2022-09-17 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_course_lesson_amount_course_student_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='attempt_amount',
            field=models.PositiveSmallIntegerField(default=3),
        ),
    ]
