# Generated by Django 4.1 on 2022-09-18 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='test_ready',
            field=models.BooleanField(default=False),
        ),
    ]
