# Generated by Django 4.1 on 2022-09-20 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0028_alter_question_text_alter_result_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='passing_score',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
