# Generated by Django 4.1.2 on 2022-10-21 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0030_result_passed'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='category',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
