# Generated by Django 4.1.2 on 2022-11-20 17:47

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0037_alter_platform_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='platform',
            name='logo',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(location='/media/logos'), upload_to=''),
        ),
    ]
