# Generated by Django 4.1.2 on 2022-11-21 15:07

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0039_alter_platform_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='student_amount',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='material',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media/lessons', location='media/lessons'), upload_to=''),
        ),
    ]
