# Generated by Django 4.1.2 on 2022-11-25 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0040_remove_course_student_amount_alter_lesson_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.course')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.studentgroup')),
            ],
        ),
    ]
