# Generated by Django 4.1.2 on 2022-12-11 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0041_term'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('bar', models.PositiveSmallIntegerField()),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exam.platform')),
            ],
        ),
    ]
