# Generated by Django 4.1.2 on 2022-12-20 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0045_activity'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
