# Generated by Django 4.1 on 2022-08-16 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner_user', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='examiner',
            name='exams',
        ),
    ]
