# Generated by Django 4.1 on 2022-08-17 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner_user', '0002_remove_examiner_exams'),
    ]

    operations = [
        migrations.RenameField(
            model_name='examiner',
            old_name='login',
            new_name='username',
        ),
    ]
