# Generated by Django 4.1 on 2022-08-17 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('examiner_user', '0003_rename_login_examiner_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Examiner',
        ),
    ]
